font_family family="FiraCode Nerd Font"
font_size 14.0
shell /bin/zsh
enabled_layouts splits,tall,fat,stack
window_padding_width 4
scrollback_lines 10000
copy_on_select clipboard
allow_remote_control yes
map ctrl+shift+enter toggle_layout stack
map ctrl+shift+f show_scrollback
map ctrl+shift+t new_tab_with_cwd
map ctrl+shift+d launch --location=vsplit --cwd=current
map ctrl+shift+s launch --location=hsplit --cwd=current
map ctrl+shift+e launch --type=overlay --cwd=current yazi
